version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "
        echo '📡 Waiting for Postgres...';
        while ! nc -z db 5432; do
          sleep 1;
        done;
        echo '🚀 Postgres is up! Running migrations and server...';
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DB_NAME=jobboard
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=job_board.settings
    env_file:
      - .env
  worker:
    build: .
    command: celery -A job_board worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=job_board.settings

volumes:
  postgres_data:
